# Generated by Django 5.0.6 on 2024-06-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sana', models.DateField()),
                ('hisoblar', models.CharField(choices=[('naqt', 'Naqt pul'), ('karta', 'Karta'), ('valyuta', 'Valyuta')], max_length=50)),
                ('chiqim_turi', models.CharField(choices=[('yolkira', "Yo'lkira"), ('tushlik', 'Tushlik'), ('salomatlik', 'Salomatlik')], max_length=50)),
            ],
        ),
    ]
